'use client';
import DashboardNav from '@/components/dashboard/nav';
import { type Metadata } from 'next'
import { ClerkProvider, SignUpButton, SignedIn, SignedOut, SignInButton, UserButton} from "@clerk/nextjs";
import Link from 'next/link';
import { Geist, Geist_Mono } from 'next/font/google'
import "../globals.css";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// export const metadata: Metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="sticky top-0 z-40 border-b bg-background">
          <div className="flex items-center h-16 px-6">
          <div className="flex w-full">
          <Link
            href="/dashboard"
            className="flex items-center space-x-2 cursor-pointer">
          <h1 className="text-lg font-bold">IT Passport がんばるぞ君</h1>
          </Link>
          <div className="ml-auto hidden md:block">  
          <SignedOut>
          <SignInButton />
          <SignUpButton>
          <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
            Sign Up
          </button>
          </SignUpButton>
          </SignedOut>
          <SignedIn>
          <UserButton />
          </SignedIn>
          </div>
          </div>
          </div>
        </header>
          <div className="container md:grid md:grid-cols-[220px_minmax(0,1fr)] md:gap-6 lg:grid-cols-[240px_minmax(0,1fr)] lg:gap-10">
          {/* sidebar */}
          <aside className="fixed md:sticky top-16 z-30 hidden md:block border-r h-[calc(100vh-4.1rem)]">
          <div className="py-6 px-2 lg:py-8">
          <DashboardNav />
          </div>
          </aside>
          {/* main contents */}
          <main className="flex w-full flex-col overflow-hidden p-4">
            {children}
          </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
